### ISSUE TITLE
Self destruct timer not working

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#1]
**Describe the bug**
Timer in self destruct ticks down to 4:59 and stops

**To Reproduce**
1. Go to your ship Security Panel
2. Click on SELF DESTRUCT
3. The time will go down to 4:59
4. It wont go further.

**Expected behavior**
The timer should go down to zero and the ship should be destroyed.

**Screenshots**
None.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
This has been broken in the original game for a while. I don't recall when it first started happening, but there are times when self-destruct would be useful, and the feature is currently straight-up broken.

**Comment by GTink911** [comment]
Self destruct is functional, the timer just doesn't tick down @CheeseJedi.

**Comment by CheeseJedi** [comment]
Good to know, however the result is pretty much the same thing to the player - unless I'm missing another way to trigger it.

**Comment by zorkind** [comment]
Fixed o7

![image](https://user-images.githubusercontent.com/11562921/94512502-8d57ff80-01f2-11eb-8a33-8010a027350d.png)

**Comment by sxygeek** [comment]
when i attempt to activate the self destruct with the "Activate" button nothing occurs, until i press the "abort" button then the warning confirmation pops up to ask if "I am sure".

once running however the time shows on the security screen as well as other displays through the ship :)

finally , when going back to cancel self destruct , the buttons to cancel are hidden behind the countdown.

**Comment by zorkind** [comment]
Geek this is not going to be reproducible now, because altho i fixed this issue, i started the implementation of the new feature that is the new time input screen.

This has been set to fixed in the original behavior where it would show you 5 minutes fixed and you would not have an option to change that.

**Comment by zorkind** [comment]
This task is a bug from VHE.

Please do not mix this task that is a bug with the 275 task that is a Feature:
https://github.com/zorkind/Hellion-Rescue-Project/issues/275

They are not the same thing.

Because of the implementation of the 275 that is NOT complete yet, you can't test this one that has been fixed previously from the 275 start. 👍
