### ISSUE TITLE
Generate loot immediately after creating a SP or new server.

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#163]
If you force all stations such as Knossos to generate loot immediately once a server has been made or or SP world created, it should fix the semi-bug of materials not appearing when you immediately warp to stations. Said issue has been verified by both me and GuiltyNeko, and is likely caused by stations not generating loot until their 20 minute cycle is completed for the first time.

**Comment by zorkind** [comment]
This is an old desync bug, now i understood what you guys were talking about before, like i said many many many times before, every time you get bellow 1 km of a station/ship you need to relog to prevent this kind of issue.

This bug exists since the 1 release of the original game, and i am aware of it, but this is not the proper solution or the proper bug.
