### ISSUE TITLE
Arges Elevator bug

### ISSUE THREAD

**Issue by TZNR316** [zorkind/Hellion-Rescue-Project#181]
**Describe the bug**
every time when docked to a station, the elevator in the arges gets very buggy and kicks me in outer space etc
**To Reproduce**
1. dock to a base
2. go to elevator
3. drive it

**Expected behavior**
smooth down going elevator
**Screenshots**

**Additional context**

**Comment by CheeseJedi** [comment]
If this is when the Arg is docked via it's airlock, this issue has been in the game for quite some time! There shouldn't be any forces other than the ships gravity yet you slide across the elevator platform as it moves when docked in this way as though there's more than one force vector in play. There was some suspicion it was related to 'stray' gravity forces from the docked-to AM, as it doesn't happen when using the anchor. 

The Arg's elevator has _always_ had some issue or another - sometimes when at warp you could be forced outside the ship when using the elevator, and as a result leave the warp bubble, resulting in unavoidable character death. I think this still happens to this day, although reports of it tailed off some time ago for the original game. That problem may be related to the issue this ticket addresses.

**Comment by codemonger** [comment]
I've encountered a bouncy Arges elevator, even when docked using the anchor but the problem was resolved by turning on the power in the Arges (not reactor power).

**Comment by zorkind** [comment]
Gravity issue fixed, the platform going down has a bit of stuttering because the platform is moving faster than the down force of the gravity (will be adjusted).

But you can move around the platform freely or stop at any place and stay.

**Comment by zorkind** [comment]
Adding this forum thread here to save my research on this topic.

https://forum.unity.com/threads/solved-elevator-problem.631084/

After working on the Gravity issue that is now solved (no mixing gravity anymore, applying room gravity correctly), i found out that the entire Elevator is animated and no matter how much i play around with the animation speed, it will never sync or wait for Physics update to happen. Even with the animation happening in the Physics update (flag set on Animator).

So the real solution here is to rework the elevator, making it a physical object moving, instead of keyframe animated.

**Comment by zorkind** [comment]
Reopening this issue, to work on the rework.
