### ISSUE TITLE
PSM and Arges reactor inequality

### ISSUE THREAD

**Issue by Minemoder5000** [zorkind/Hellion-Rescue-Project#212]
**Is your feature request related to a problem? Please describe.**
The PSM output and HE3 consumption is an order of magnitude more efficient than the Arges reactor, with the PSM producing 500 energy at the cost of 0.6 HE3 per hour and the Arges producing 750 power at the cost of *8* HE3 per hour. Both reactors are stock with no components.

**Describe the solution you'd like**
The reactor of the Arges needs to have its resource consumption lowered to be more in line with the PSM, but still consume more as it produces more power.

**Describe alternatives you've considered**
A larger HE3 capacity for the Arges.
More power storage for the Arges.
Higher solar panel output so that it can function for a longer period without running the reactor.

**Additional context**
Power supply screen for both the PSM and Arges
https://imgur.com/a/oNJYt0v

**Comment by GuiltyNeko** [comment]
The PSM reactor is on a _dedicated_ platform for it, so it's going to be more efficient. The PSM reactor _also_ has 4 catalyst slots and 3 CCFG slots, whereas the arges reactor has only 2 and 1 of each. The arges reactor is inefficient in terms of resource consumption because it's relatively tiny compared to the PSM reactor. The PSM reactor is huge, you can see how big the oval is, that's the reactor. The arges reactor is very small, so it has to consume much more fuel.

**Comment by zorkind** [comment]
I am rejecting this, because you can always customize this in the server settings files, so perhaps in 0.2.0 we can make sure the values make sense.
