### ISSUE TITLE
Add a borderless fullscreen option

### ISSUE THREAD

**Issue by Minemoder5000** [zorkind/Hellion-Rescue-Project#214]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Borderless fullscreen.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zorkind** [comment]
Unfortunately duo to some Unity issues this wont be possible, i found out some tricks to make it happen but they are not from unity themselves and it can slow down the performance of the game significantly.

I am sorry but i will have to say no to this one. Because of Unity limitations.

The new unity version 2019+ has this fixed tho, unfortunately our unity version is 2018.

**Comment by zorkind** [comment]
I added one option that might help a bit tho, its called "RestrictCursorToGame" if this is set to false, and you have a menu open or a terminal screen and your cursor is visible, you can go outside the game window, otherwise it will restrict you to the game bounds, but it's not very good, and that is what the Vanilla uses, it's not very good cause, you can accidentally click off screen because of how this is implemente in this version of Unity.

Not perfect, but helps.
