### ISSUE TITLE
Fix missing Steropes door

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#234]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The door in the steropes is missing, add it back.

**Describe alternatives you've considered**
Remove the door frame.

**Additional context**
None.

**Comment by CheeseJedi** [comment]
I've thought about this since the Steropes was introduced - why is there a door frame with no door? My conclusion was that it was unnecessary, and added little benefit to the use of the ship. The door was probably removed (assuming there was ever one there), but the frame remained (easier than modifying the ship's interior geometry).

Adding a door there will require additional work to split the storage room and hallways in to two separate rooms, plus defining new a new doorway - and I suspect this is going to be _seriously non-trivial_.

What value would it add, other than increasing the number of hacking tools required to gain control of a vessel?

Perhaps switching out the 3D model of the door frame that's used in this spot for something that doesn't look like it's got 'channel guides' for a door to slide through would male it look less like there's a door missing.

**Comment by zorkind** [comment]
![image](https://user-images.githubusercontent.com/11562921/104958020-0c459380-59ae-11eb-85cd-60a2b8c2de5f.png)
![image](https://user-images.githubusercontent.com/11562921/104958036-12d40b00-59ae-11eb-9229-152129010e70.png)
![image](https://user-images.githubusercontent.com/11562921/104958048-19628280-59ae-11eb-9fdb-aa478b9328a6.png)
![image](https://user-images.githubusercontent.com/11562921/104958064-1ebfcd00-59ae-11eb-903b-c9479b1816c4.png)

Decided to use the same door the SDS corridor modules use and i love the results. ;)
