### ISSUE TITLE
Space Stardust bubble up on target change when EVA

### ISSUE THREAD

**Issue by zorkind** [zorkind/Hellion-Rescue-Project#246]
**Vanilla / HRP**
Vanilla.

**Client Version**
Vanilla

**Describe the bug**
When you are in EVA there is a stardust effect that helps you see your movement in space.
Depending on your current target the stardust will reshape itself around that target, and when that happens you will notice a bubble effect of the stardust, specially if the target is rotating too fast, the stardust will rotate along its axes too fast to be believable.

**To Reproduce**
1. Go to space EVA
2. Use the mouse wheel to change targets
3. You will notice how the stardust behaves wonky

**Expected behavior**
The stardust should be in space in a constant manner not changing with the target and not bubbling up.

**Screenshots**
None.

**Additional context**
None.

**Comment by zorkind** [comment]
Fixed this by pointing the stardust to Hellion sun, this way it has a constant point in space and wont move by target changes.

**Comment by CheeseJedi** [comment]
I'm not sure where the bug was for this issue...? I'd argue this issue isn't (wasn't ever) a bug and is one of the things that are 'working as intended' in the original game.

Based on my understanding of the lore/etc. it's not 'star dust' or anything physical at all that you're seeing - It's a _visualisation generated by the suit's hud system_ as a navigation aid while in EVA and is intended to be fixed _relative to your selected target_ to help you judge and match speed in your suit (as a visual addition to the 2-axis velocity indicator on the hud).  I've found it incredibly useful when approaching spinning derelicts, for example, especially so if in a debris field.

Seeing as the whole system is now 'fixed' to the star, unless you plan on attempting to velocity match Hellion itself in your suit (actually impossible) I don't see how this could be an improvement, or even remotely useful, at all - instead I see the hobbling of a working feature; Fixing it to the star makes it useless in all situations and reduces it to purely a visual effect that has little bearing on anything else going on in the game world. :/

Sorry guys I don't like this one at all 👎

**Comment by zorkind** [comment]
That's totally fine, just turn it off in the client settings, all good. 

Some people like that to work differently and everyone's point of view is valid and it was something i could do, no reason not to, since it's optional as everything else.
👍

**Comment by zorkind** [comment]
The option was added to the new client settings json file (the one that resides in the game folder, not the original settings file), it will come for HRP default to this new behavior, but feel free to turn it off.

I will change this from bug to Suggestion, although i have to say, this "feature" of visual aid you say this is for, not many people know this is the intended usage of this, since it clearly appears to be 'stardust' so i don't blame people that think it should behave as i have made it behave, and think this is a bug, to them this "effect" is annoying and make no sense, and you can still see your movement relative to Hellion, you just didn't see the result of the change so you couldn't know but you still see your movement very clearly, when you stop your movement, the dust stay still, so it's not impossible, since it works.

Perhaps it is a problem of communication, or of perception of what the HUD give you as 'visual aid' which to me is kind of lacking, specially related to the the 2-axis velocity indicator you talked about, to me it should be more detailed.

For example the velocity indicator turns red when you reach some proximity to the target you going towards no mater what speed you are traveling, even at 0.0m/s it gets red, who can guess what that means just by looking at it without having previous knowledge about it?

So i can't blame the players specially the ones that got their game from the free event and know absolutely nothing about the past of the project to understand these things without proper documentation.

But this is a good discussion and it's always useful to improve the game. 👍

**Comment by GuiltyNeko** [comment]
Perhaps a _better_ visual aid that tells you, for example, where _up_ is on a station, as well as the locations of ports and _their_ upwards directions. And then something that tells you the exact rate of spin on each axis.

**Comment by zorkind** [comment]
It was detected some issues with this change, it is a known bug, but it has a low priority right now.
The effect will remain on while on docking screen with "static non moving" dusts on the screen.
