### ISSUE TITLE
Suit space for 4 in the LSM

### ISSUE THREAD

**Issue by GTink911** [zorkind/Hellion-Rescue-Project#95]
**Is your feature request related to a problem? Please describe.**
Its annoying to only be able to stock a LSM with 2 suits when there is space for 4 people.

**Describe the solution you'd like**
Add another suit rack to LSMs.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by GuiltyNeko** [comment]
Technically there exists space on the racks for another 2 suits.

**Comment by GTink911** [comment]
Screenshot?

**Comment by GuiltyNeko** [comment]
I could swear that the slots were large enough, but it turns out they aren't. You can fit a single full suit on the racks, but not a second one.

**Comment by CheeseJedi** [comment]
As suit parts (helmet + jetpack) can remain in the suit body, and given that there's two suit positions ( = 6 shelf positions, although the helmet slots at the top seemed smaller) perhaps a workaround to this would be _to allow suit body pieces to be placed in the lower slot of the suit rack,_ - this would allow 4 complete suits to be stored in the lower 4 shelves of the suit rack.

The two lower shelves would need to be modified to accept the suit body parts (all tiered versions) to make this work. Perhaps the top ones could be modified in this way also, although there's not much room. 

Each shelf 'slot' has a number of sub GameObjects (one per object type that the shelf accepts) that the part is parented to, and this applies the slot's GameObject transform (position, rotation as well as scale) to the placed item - essentially the models are resized to fit in the slots, although these scale changes need to be fairly small otherwise it would become quite noticeable that the part is changing size when it goes on/off a shelf!

I wonder if it would be worth doing this to all the suit racks in all modules/ships?

**Comment by zorkind** [comment]
Cheese i understand your proposal, but i am making a more complex change to the LSM module, making it more interesting.

You might not like it, i don't know, but the way i am doing it will increase the usage of the space and promote pvp by adding cover to the room.

Take a look at my changes:
![image](https://user-images.githubusercontent.com/11562921/92685960-1f18cf00-f30f-11ea-9e61-40690f396b60.png)

![image](https://user-images.githubusercontent.com/11562921/92686045-47083280-f30f-11ea-8fa9-74517b933b37.png)

![image](https://user-images.githubusercontent.com/11562921/92686099-5edfb680-f30f-11ea-9b41-cbc29bafca44.png)

![image](https://user-images.githubusercontent.com/11562921/92686150-7cad1b80-f30f-11ea-8262-dcb9267dafad.png)

![image](https://user-images.githubusercontent.com/11562921/92686239-a403e880-f30f-11ea-9f29-9f2a1b392bdb.png)


As you can see i changed the floor and quite a lot of furniture around in the module.
I believe this is a much more efficient use of the space.
If we find that the space is too crowed, we could remove those 2 sloped pillars from each side and that will give us more area to walk around, but i think this is not too bad, it would be best to have that extra space in case a player logout in that corridor.

But this way we will fix all the issues with this module, it will have ammo slots, weapon slots and suit slots.

The issue with the suit was not only the need for 4 slots, we had some weapon slots in the wall but no ammo.
They 'fixed' that by adding the shelves, but i honestly think those shelves could go, i just didn't remove them, because i want to test first, and we have the space for them, so, they don't bother me too much.

Anyway, this design was conceptualized together with the community in the Discord and they liked it, so we will give it a try 👍
